# Generated by Django 3.1.12 on 2025-04-17 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0006_product_brand'),
        ('accounts', '0004_auto_20250416_0210'),
        ('deals', '0002_auto_20250416_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('deals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.deal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sellerprofile')),
            ],
        ),
    ]
