# Generated by Django 3.1.12 on 2025-04-17 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20250417_1842'),
        ('deals', '0002_auto_20250416_0942'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproduct',
            name='deals',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='deals.deal'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
