# Generated by Django 3.1.12 on 2025-04-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20250417_1936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerProduct',
        ),
    ]
