# Generated by Django 3.1.12 on 2025-04-20 00:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_auto_20250416_0942'),
        ('shop', '0007_auto_20250417_1842'),
        ('accounts', '0008_auto_20250419_0521'),
        ('seller', '0004_sellerproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproduct',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sellerproduct',
            name='is_active_seller',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='deals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_products', to='deals.deal'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='accounts.sellerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='sellerproduct',
            unique_together={('seller', 'product')},
        ),
    ]
