# Generated by Django 3.1.12 on 2025-04-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20250420_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
