# Generated by Django 3.1.12 on 2025-04-14 03:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='details',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
