# Generated by Django 3.1.12 on 2025-04-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sellerprofile_gst_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
