# Generated by Django 3.1.12 on 2025-04-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_sellerprofile_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='customer_profiles/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='seller_profiles/'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='bank_account',
            field=models.CharField(max_length=100),
        ),
    ]
