# Generated by Django 3.1.12 on 2025-04-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_sellerprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
