# Generated by Django 3.1.12 on 2025-04-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentationsection',
            options={},
        ),
        migrations.AlterField(
            model_name='documentationsection',
            name='icon',
            field=models.CharField(blank=True, help_text='Example: 📘 or 🛠️', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentationsection',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
