# Generated by Django 3.1.12 on 2025-04-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_auto_20250415_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationsection',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
