# Generated by Django 3.1.12 on 2025-04-15 08:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_auto_20250415_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='documentation_images/'),
        ),
        migrations.AlterField(
            model_name='documentationsection',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
