# Generated by Django 5.2 on 2025-04-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0004_auto_20250415_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationsection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
