# Generated by Django 3.1.12 on 2025-04-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20250413_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_todays_deal',
            field=models.BooleanField(default=False),
        ),
    ]
