# Generated by Django 3.1.12 on 2025-04-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_is_todays_deal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_todays_deal',
        ),
    ]
