# Generated by Django 3.1.12 on 2025-04-15 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sellerprofile_gst_number'),
        ('shop', '0004_remove_product_is_todays_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.sellerprofile'),
        ),
    ]
