# Generated by Django 5.2 on 2025-04-20 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20250417_1842'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='shop_produc_id_f21274_idx',
            old_fields=('id', 'slug'),
        ),
    ]
